---
apiVersion: v2
name: zabbix
version: 0.1.2
appVersion: 4.4.5
description: Zabbix is a mature and effortless enterprise-class open source monitoring solution for network monitoring and application monitoring of millions of metrics.
keywords:
  - zabbix
  - monitoring
  - metics
home: https://www.zabbix.com/
icon: https://assets.zabbix.com/img/logo/zabbix_logo_500x131.png
source:
  - https://github.com/cetic/helm-zabbix
maintainers:
  - name: AyadiAmen
    email: amen.ayadi@cetic.be
    url: https://github.com/AyadiAmen
  - name: alexnuttinck
    email: alexandre.nuttinck@cetic.be
    url: https://github.com/alexnuttinck
dependencies:
  - name: postgresql
    version: ~9.4.1
    # repository: https://kubernetes-charts.storage.googleapis.com/
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
